### ISSUE TITLE
[Feature Request] Tabs in the show view

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#1]
@soufiene-slimi suggested this in https://github.com/Laravel-Backpack/CRUD/discussions/3037 but I don't think having it as a Discussion is productive enough - the information might get lost. That's why I started this repo, where we can move Feature Requests to talk about them before they're actually implemented. Let's see how that goes. @ziming has also pitched in. For now:

# Feature Request

### What's the feature you think Backpack should have?

Tabs like the create/edit views

### Have you already implemented a prototype solution, for your own project?

Not yet

### Do you see this as a core feature or an add-on?

Core feature

**Comment by LemarinelNet** [comment]
Hi there,
Is there any news of this feature ? 

I've not looked at the code, but I wonder if this feature consist of just copying the behaviour (and code) of the create/update tab feature ?

If I can help implementing, I can give it a try ;)

**Comment by tabacitu** [comment]
This turned into a PR 😄 Thanks @LemarinelNet - let's move the conversation to your PR https://github.com/Laravel-Backpack/CRUD/pull/3314

**Comment by LemarinelNet** [comment]
You're welcome ! 
This was not a big job (even I haven't finished it completely :D )
