### ISSUE TITLE
[Feature Request] Default value(s) for all field types

### ISSUE THREAD

**Issue by WrdVdb** [Laravel-Backpack/ideas#103]
# Feature Request

### What's the feature you think Backpack should have?

I would like that all field types can have a default value. In my case I need it with multiple selects (select_multiple, select2_multiple, ...)

### Have you already implemented a prototype solution, for your own project?

Yes, I made a custom view for the select2_multiple field type:

I changed

```php
@if (isset($field['model']))
    @foreach ($field['options'] as $option)
        @if( (old(square_brackets_to_dots($field["name"])) && in_array($option->getKey(), old($field["name"]))) || (is_null(old(square_brackets_to_dots($field["name"]))) && isset($field['value']) && in_array($option->getKey(), $field['value']->pluck($option->getKeyName(), $option->getKeyName())->toArray())))
            <option value="{{ $option->getKey() }}" selected>{{ $option->{$field['attribute']} }}</option>
        @else
            <option value="{{ $option->getKey() }}">{{ $option->{$field['attribute']} }}</option>
        @endif
    @endforeach
@endif
```
To 

```php
@if (isset($field['model']))
    @foreach ($field['options'] as $option)
        @if( (isset($field['default']) && in_array($option->getKey(),$field['default'])) || (old(square_brackets_to_dots($field["name"])) && in_array($option->getKey(), old($field["name"]))) || (is_null(old(square_brackets_to_dots($field["name"]))) && isset($field['value']) && in_array($option->getKey(), $field['value']->pluck($option->getKeyName(), $option->getKeyName())->toArray())))
            <option value="{{ $option->getKey() }}" selected>{{ $option->{$field['attribute']} }}</option>
        @else
            <option value="{{ $option->getKey() }}">{{ $option->{$field['attribute']} }}</option>
        @endif
    @endforeach
@endif
```

And the default is set like this:

```php
$this->crud->addField([
    'label' => "Contact types",
    'type' => 'select2_multiple',
    'name' => 'contactTypes',
    'default' => [1,2]
]);
```

### Do you see this as a core feature or an add-on?

I think all field types should allow default values as a core feature.

As far as I can see these field types lack a default value option:

enum
page_or_link
password
relationship
select_multiple
select2_multiple

**Comment by maurohmartinez** [comment]
@tabacitu I checked the fields mentioned and the only one that doesn't support default value is `password`.
I adjusted it so I am ready to create the PR. Is that ok? What do you think?

**Comment by tabacitu** [comment]
That's excellent Mauro. Please create the PR, assign Pedro or Jorge to double-check, and close this issue, let's put it behind us 💪

Cheers!

**Comment by tabacitu** [comment]
Awesome! Thanks @maurohmartinez , great to know we're consistent with `default` now. Pfiew!
