### ISSUE TITLE
[Feature Request] Possibility to create custom tables with datatable functionality

### ISSUE THREAD

**Issue by IoanAndrei97** [Laravel-Backpack/ideas#105]
# Feature Request

### What's the feature you think Backpack should have?
It will be awesome if we could add the datatable functionality ( search, pagination, etc ) on custom tables that are created on custom blade files.
For example, I created a custom show page because I need multiple tables in the same page and I can't ( or don't know how? ) add the datatable functionality to my custom ( "hand made" ) tables.

### Have you already implemented a prototype solution, for your own project?
No.

### Do you see this as a core feature or an add-on?
Yes. I think many users need this because if we use backpack in a complex project very often we need to create tables that have to be paginated, filtered etc.

**Comment by tabacitu** [comment]
Totally agree to a CRUD widget (basically an embeddable CRUD List View) - I see there's already an open issue for it in https://github.com/Laravel-Backpack/ideas/issues/108 so let's move the conversation there please.

@IoanAndrei97 , thanks for opening the issue 🙏
