### ISSUE TITLE
2 relationship fields depending on each other gives error

### ISSUE THREAD

**Issue by matthbon** [Laravel-Backpack/ideas#106]
Hi,

I am trying to have 2 relationship fields depending on each other. But it gives Maximum call stack exceeded when trying to select an option.

My model (it is a polymorph relation, but this way I can choose 1 of the fields)
```
class CategoryMenu extends Model
{
    use Flushable, CrudTrait;

    public $appends = [
        'category',
        'tag',
    ];
/**
     * @return BelongsTo
     */
    public function tag(): BelongsTo
    {
        return $this->belongsTo(Tag::class, 'model_id', 'id', 'model_type');
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'model_id', 'id', 'model_type');
    }
    }
```

My fields
```
$this->crud->addField([
                'label' => 'Tag',
                'type' => 'relationship',
                'name' => 'tag',
                'entity' => 'tag',
                'attribute' => 'name',
                'model' => Tag::class,
                'ajax' => true,
                'minimum_input_length' => 3,
                'dependencies' => ['category'],
                'include_all_form_fields'  => false,
            ]);
            $this->crud->addField([
                'label' => __('or') . ' ' . __('Category'),
                'type' => 'relationship',
                'name' => 'category',
                'entity' => 'category',
                'attribute' => 'category_name_with_slug',
                'model' => Category::class,
                'ajax' => true,
                'minimum_input_length' => 3,
                'dependencies' => ['tag'],
                'include_all_form_fields'  => false,
            ]);
```

How the fields look
<img width="1123" alt="Screen Shot 2021-02-09 at 12 34 02 PM" src="https://user-images.githubusercontent.com/14940974/107358214-65977300-6ad3-11eb-86c4-3e0023f38cfb.png">

And when trying to select the Tag relation it hangs and gives this error
<img width="1680" alt="Screen Shot 2021-02-09 at 12 34 49 PM" src="https://user-images.githubusercontent.com/14940974/107358268-77791600-6ad3-11eb-9cad-01ce4b62f7ac.png">

So the Category relationship is empty, but the Tag field is not selecting.
Without the dependencies it works perfect.
Am i doing something wrong? Or is this a bug?

Thanks,
Matthijs

**Comment by pxpm** [comment]
Hello @matthbon 

The error you are getting is because you are making 2 fields depend on each other simultaneously. 

So when you change `tag` -> `category` changes -> when `category` changes -> `tag` changes -> when `tag` changes -> `category` .. 

You see where I am going? A never ending loop of changes! 


> When category changes, products is reseted. So product depend on category. 

```php
 [    // SELECT2
                    'label'         => 'Category',
                    'type'          => 'relationship',
                    'name'          => 'category',
                    'ajax'        => 'true',
                ],
                [ // select2_from_ajax: 1-n relationship
                    'label'                => "product", // Table column heading
                    
                    'name'                 => 'products', // the column that contains the ID of that connected entity;
                    'ajax' => true,
                    'attribute'            => 'name', // foreign key attribute that is shown to user
                    //'data_source'          => backpack_url('dummy/fetch/products'), // url to controller search function (with /{id} should return model)
                    'placeholder'          => 'Select an product', // placeholder for the select
                    'include_all_form_fields' => true, //sends the other form fields along with the request so it can be filtered.
                    'minimum_input_length' => 0, // minimum characters to type before querying results
                    'dependencies'         => ['category'], // when a dependency changes, this select2 is reset to null
                    'method'                    => 'POST', // optional - HTTP method to use for the AJAX call (GET, POST)
                ]
            ]
```

I don't think this is a bug, so I am going to close this. 

If you think I am wrong, please re-open. Sometimes I am :)

Best,
Pedro

**Comment by matthbon** [comment]
Hi Pedro,

Thanks for your time to look at it. I understand what you mean and was already thinking this was going to be the case.
 Is there another way I can achieve what i want? Can i do relationship fields in the checklist_dependency. for example?

Best,
Matthijs

**Comment by pxpm** [comment]
Hello @matthbon 

I guess you could create a select field with 2 options (tag/category), then use an ajax field like you do, with `include_all_form_fields` that depends on the first select with the two options. 

That way you can switch between `tag` or `category` in first select and when that happens your ajax select with the options is reseted. 

Let me know if this helps.

Best,
Pedro

**Comment by matthbon** [comment]
Hi @pxpm,

Tried your solution and works like a charm. Thanks for your time.

Cheers,
Matthijs
