### ISSUE TITLE
Submenu indent in sidebar

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/ideas#115]
Not sure whether this is already covered in 4.2 but I'm now using the blue theme and there the submenu's are not indenting. I've fixed this for now with a custom CSS file that overrides with this:
```css
.sidebar .nav-dropdown>.nav-dropdown-items>.nav-item>.nav-link {
    padding-left: 2rem;
}
```
Maybe this needs to be fixed upstream for the blue theme?

**Comment by malle-pietje** [comment]
Screenshot of the results:
![Screenshot 2021-11-15 134914](https://user-images.githubusercontent.com/12016131/141784891-59e91fec-85a7-435e-ad22-8aabfacfc4e7.png)

**Comment by malle-pietje** [comment]
php artisan backpack:version
### PHP VERSION:
PHP 7.4.9 (cli) (built: Jul  5 2021 13:33:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.69.0@545181da688db64fed6d8427e55f630a90ca0d32

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee

**Comment by promatik** [comment]
Hi @malle-pietje!

I can see the value for padding is `padding-left: 1.5rem;` in both blue and the original purple theme.
I believe it always was like this. Can you tell me what do you feel to be unaligned?

`1.5rem`
![image](https://user-images.githubusercontent.com/1838187/141816450-96720164-6000-4aec-b56d-74bb0e267f62.png)

`2.0rem`
![image](https://user-images.githubusercontent.com/1838187/141816498-307dd39b-fa4d-47ad-9eb7-2497402f8331.png)

**Comment by malle-pietje** [comment]
Actually in all my projects it looks like this:
![image](https://user-images.githubusercontent.com/12016131/141821334-dd3c8225-8af5-410a-9ec0-d9e9cfcf9ec0.png)

This is the HTML code:
```html
    <!-- Users, Roles, Permissions -->
    <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#"><i class="nav-icon la la-users"></i> Authenticatie</a>
        <ul class="nav-dropdown-items">
            <li class="nav-item"><a class="nav-link" href="http://project.local/admin/user"><i class="nav-icon la la-user"></i> <span>Gebruikers</span></a></li>
            <li class="nav-item"><a class="nav-link" href="http://project.local/admin/role"><i class="nav-icon la la-id-badge"></i> <span>Rollen</span></a></li>
            <li class="nav-item"><a class="nav-link" href="http://project.local/admin/permission"><i class="nav-icon la la-key"></i> <span>Permissies</span></a></li>
        </ul>
    </li>
```

**Comment by malle-pietje** [comment]
CSS:
![image](https://user-images.githubusercontent.com/12016131/141821975-1405f4cb-2e7c-4d0c-a38b-ffc59cf1f5fe.png)

**Comment by malle-pietje** [comment]
Maybe also relevant, here's the styling config for the sidebar:
```php
'sidebar_class' => 'sidebar sidebar-dark bg-dark',
```

**Comment by promatik** [comment]
Super strange, so in your case you have no padding at all?

I just checked the `blue-bundle.css` and it has the rule;
https://demo.backpackforlaravel.com/packages/backpack/base/css/blue-bundle.css

![image](https://user-images.githubusercontent.com/1838187/141828917-07fe7bde-3942-4342-822b-3c3f6cf3b1c9.png)

The rule that should be being applied in that case is this one;
```css
.sidebar.sidebar-pills .nav-dropdown .nav-link:not(.nav-dropdown-toggle) {
    padding-left:1.5rem
}
```

@malle-pietje can you check the rendered HTML to see if it follows this rule?
`.sidebar.sidebar-pills .nav-dropdown .nav-link:not(.nav-dropdown-toggle)`

**Comment by malle-pietje** [comment]
@promatik Here is the Inspection output for the "Users" menu option:
![image](https://user-images.githubusercontent.com/12016131/141966800-18c04794-a28e-4e9f-b593-41060bb1d283.png)

**Comment by promatik** [comment]
Hi @malle-pietje, thank you for your report, I'm glad you found the issue. I don't know if we can do anything about it.

I'll let @tabacitu decide on it, we would need to change some custom rules on backstrap to allow this.
https://github.com/DigitallyHappy/BackStrap/blob/master/src/scss/_custom.scss#L241

**Comment by tabacitu** [comment]
Hmmm... Is there an _easy way_ to expand the scope of our indenting selector @promatik , so that the indentation takes place for all sidebars not just `sidebar-pills`? If there's an _easy way_ to do it, let's do it. Otherwise, if it requires heavy customization of a CoreUI feature... let's not. That'd make it even more difficult for us to upgrade to the next CoreUI version in a few months, so maybe we're able to do it afterwards.

**Comment by promatik** [comment]
I think yes, it is possible;
![image](https://user-images.githubusercontent.com/1838187/142887370-e821b166-0dfb-4422-be74-d00223671af2.png)

I'll move this to "to do" 4.2 – after launch.
