### ISSUE TITLE
[Feature Request] List Operation -- Option to show pagination links above table.

### ISSUE THREAD

**Issue by trip-somers** [Laravel-Backpack/ideas#117]
# Feature Request

### What's the feature you think Backpack should have?

Pagination currently resides at the bottom of the list table. The default minimum number of rows is 25 which is already long enough to not be able to see the top when a new page is loaded. Since changing pages does not also scroll up, the user who is scanning the rows has to manually scroll up to view the top, then back down to go to the next page (and repeat). This problem is exaggerated for larger rows-per-page values.

There are two solutions that seem obvious: autoscroll when changing pages or add pagination links above the list table. Autoscroll is likely more disruptive to people accustomed to the current interface, so an option to duplicate pagination links at the top of the table seems like the best bet.

I would be happy with either of these approaches:

* Show pagination at the top and bottom with an option to disable either.
* Add an option/setting to turn on 'top' pagination.

### Have you already implemented a prototype solution, for your own project?

I have not attempted this myself yet.

### Do you see this as a core feature or an add-on?

Core feature.

**Comment by tabacitu** [comment]
Since there was no interest in this until now, I'm going to close the issue (as in... not prioritize doing it). But if you've googled this, landed on this issue and you think we're wrong in closing this, please let us know, we can re-open.

Cheers!
