### ISSUE TITLE
[Feature Request] Using widgets with tabs

### ISSUE THREAD

**Issue by izica** [Laravel-Backpack/ideas#118]
Using widgets with tabs same way as tabs in fields

**Comment by tabacitu** [comment]
Hey @izica - I see no reason why it would be impossible to create a `tabs` widget, that contains a card with tabs - something like https://backstrap.net/base/tabs.html

Is this what you meant?

**Comment by izica** [comment]
@tabacitu Hi, not that way, I would like to be able to insert widgets in deifferent tabs,
For example:
1 tab Chart widget
2 tab Other widget
3 tab ...

Like you can put fields in defferent tabs by `tab` option

**Comment by tabacitu** [comment]
Oh... I get it now, thanks for the explanation. **Unfortunately, I don't think this would useful to a lot of people, so I don't think we're going to build this in the near future.** It shouldn't be too difficult to build for you project, though. I see two options:

### (A) a `tab` widget
- add a `tab` wrapper attribute to the widgets, which will output that attribute on the parent div;
- create a "tabs" widget that has a container div + JS that moves all items with a defined `tab` to their respective tab;


### (B) custom HTML for the tab, then in each tab include the wanted widget
- create a `dashboard.blade.php` file for example
- inside it you can have the tabs as HTML
- inside each tab where you want a widget, you can do `@include(Widget::make()->type('progress')->description('Registered users'))`

I think (A) could be useful to you if you want to define the Widgets in the Controller. Option (B) is easier if you want to define them in the view.

Hope it helps! If you anybody else stumbles onto this and thinks this should be a core feature, please reply here, I'm often wrong like anybody else 😉

Cheers!

**Comment by tabacitu** [comment]
Also, @izica , if you do end up with a pretty general solution for this, please consider copy-pasting it here, might help someone else 🙏
