### ISSUE TITLE
Can i've create form in list view [Feature Request]

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/ideas#121]
# Feature Request

### What's the feature you think Backpack should have?
I want to have create form in list view because  i can cross check data in list view when i use create form.
??

### Have you already implemented a prototype solution, for your own project?

??

### Do you see this as a core feature or an add-on?

??

**Comment by tabacitu** [comment]
There is no way to easily do this in Backpack. But you can add a widget, and that widget can contain a form. See https://backpackforlaravel.com/docs/5.x/base-widgets#creating-a-custom-widget-type-1 for info on how to create a widget.
