### ISSUE TITLE
[Feature Request] Google Two-Factor Authentication (2FA)

### ISSUE THREAD

**Issue by mcaif** [Laravel-Backpack/ideas#132]
Missing some security when accessing the application. I have reviewed possible libraries that could be useful, but since BackPack has its own user login system, it would be very good if the 2FA access was within the core.

Some examples: 
- [antonioribeiro/google2fa-laravel](https://github.com/antonioribeiro/google2fa-laravel).
- [Laragear/TwoFactor](https://github.com/Laragear/TwoFactor) -> [info](https://itnext.io/laravel-free-two-factor-authentication-5a4be723dfa7).

Am I too wrong to request this feature?

**Comment by pxpm** [comment]
@mcaif you should be able to follow: https://backpackforlaravel.com/docs/5.x/base-how-to#customizing-the-auth-controllers and do your own auth flow that includes 2f

**Comment by mcaif** [comment]
Thanks for your response!. I'll try that option.
