### ISSUE TITLE
[Filters] Make hidden filters

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/ideas#140]
I want to create a filter but without beign shown in the UI. 

![image](https://user-images.githubusercontent.com/8792209/166458830-a5fd70a7-23cb-4596-95a3-4cc723821d3b.png)

I know i can achieve this with css but maybe a hidden filter?

```
$this->crud->addFilter([
      'type'  => 'hidden',
      'name'  => 'id',
  ], 
  false, 
  function($value) {
      $this->crud->addClause('where', 'id', '=', $value);
});
```

**Comment by pxpm** [comment]
@aberaldo you can try something like:

```php
public function setupListOperation() {
// ... your code
if(request()->has('some_key')) {
$this->crud->query = $this->crud->query->where('some_key', request('some_key'));
}
}
```

It's pseudo code, but something along those lines should get you going. 

Let me know, cheers.

**Comment by aberaldo** [comment]
@pxpm excelent it works!. I will close this. 
Thanks!
