### ISSUE TITLE
Return link resets filters

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/ideas#141]
Hello,

I dont know if its a bug or im doing sth wrong. But im having trouble with list view url with filters.
What ive develop is a button that if click it opens a new tab with the crud list view with a filter applied passing the query in the url.
Like this 

![image](https://user-images.githubusercontent.com/8792209/166941697-a49eb213-fffb-4deb-b1af-9496aa72ed8e.png)

If enter to the update view it show a return link to the list but on returning the filters are reseted.
![image](https://user-images.githubusercontent.com/8792209/166942077-e0594955-de42-4400-ac29-e1acb91f6e96.png)

Ive the persist filter option on true and this only happens if the user click on that button. 
Filtering manually then going to the update view and click in the return link works well. 

Any idea?

**Comment by tabacitu** [comment]
Sounds like a bug to me! Let's close this in favor of https://github.com/Laravel-Backpack/CRUD/issues/4360

Thanks @aberaldo !
