### ISSUE TITLE
Possible far future replacement for datatables? Gridjs

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/ideas#145]
Felt this is better for ideas rather than discussions

Some days ago I saw this trending high on the orange site

Seem like a good alternative to datatables for the future since datatables is heavily dependent on jQuery

https://gridjs.io/

But it may not be needed as well if normal tables with livewire can do what you all wanted or if there are better alternatives by then.

It also has a laravel integration (but it's last updated in end 2021)

https://gridjs.io/docs/integrations/laravel

**Comment by tabacitu** [comment]
Huh - this is really nice. Good find @ziming , didn't know about it. 

But like you said, I don't think think this will be necessary - the Livewire component should be built in such a way that it can be used for multiple purposes:
- as a main operation
- as a widget in a dashboard
- as a widget in a different operation

🎉 I'll close the issue, but if I'm wrong on the above we can always come back to this.

Thanks for sharing!
