### ISSUE TITLE
allow `escaping` per table column and not the whole table column

### ISSUE THREAD

**Issue by basselhossam** [Laravel-Backpack/ideas#146]
# Bug report

### What I did

I have a json array that I use column type table for rendering it and one of its columns contains html so I used `->escaped(true)` but still the html is rendered as text

### What I expected to happen

html to be rendered correctly

### What happened

html was rendered as text

### What I've already tried to fix it

when I investigated the vender package I found that in `resources/views/columns/table.blade.php` there is no check when rendering the value
```
@foreach($column['columns'] as $tableColumnKey => $tableColumnLabel)
	<td>
                {{ $tableRow[$tableColumnKey] ?? '' }}
	</td>
@endforeach
```
so I suggest to update it to be 
```
@foreach($column['columns'] as $tableColumnKey => $tableColumnLabel)
	<td>
                 @if ($column['escaped'])
                       {{ $tableRow[$tableColumnKey] ?? '' }}
                 @else
                      {!! $tableRow[$tableColumnKey] ?? '' !!}
                 @endif
	</td>
@endforeach
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.21 (cli) (built: Sep 30 2021 13:37:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.83.15@bf8fbdd9061611b2c05562fa14f6987cc5145d78

### BACKPACK VERSION:
5.0.20@a6b183978fc7c206ce9cd437e5c9b96f8fb6823f

**Comment by basselhossam** [comment]
@pxpm any updates regarding this I'd be happy to provide a PR for this if that would help

**Comment by basselhossam** [comment]
@tabacitu ok I have 2 comments regarding this and why I think it should be added
1- for maintaining the convention across all columns since we have the escaped property across all columns and you allow the user to handle this on there own risk so it fells weird to only exclude the table from this
2- is why I'm needing this in the first place so the idea is I have this scheme
form, form_fields, form_submission, form_sumission_answers
so basically it's a dynamic form generator and the form_fields have and based on this type the answer of the field can have different representation in the DB either text, number, date and so on
one of the fields type is json object
so I'm using the table column to show the answers of the form_submission and the issue happen when trying to display the json field value because now I need a table within the table so I'm mutating value to render html
so it appears like so
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/29305349/182421538-41227f99-585f-4067-9e07-fb83ffa32e78.png">
if there is another column that can achieve what I'm going for that's ok with me

hope that I made it clear now
Cheers!

**Comment by Rashed-Bahnasi** [comment]
@tabacitu 
i have same issue
![2024-07-06_165649](https://github.com/Laravel-Backpack/community-forum/assets/107884331/cd7a73e8-5ec8-41e1-91a3-586f565ae15c)
