### ISSUE TITLE
Make "related entries in the same form" comply with relationships regarding repeatability

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/ideas#151]
I think this feature [ https://backpackforlaravel.com/docs/5.x/crud-fields#manage-related-entries-in-the-same-form-create-update-delete ] is awesome, except it doesn't abide by relationship rules.
If a model has a hasOne relationship then surely it shouldn't show a "+ New Item" button after displaying one sub form?

Is this doable I wonder?

Cheers

**Comment by pxpm** [comment]
@fronbow Hello.
I am not sure I totally understood your question, but I think if the relationship is `HasOne` and you are using subfields, the `+ New item` is hidden as soon as 1 row is added in the input. If you want to force that row to be present at start you can configure `min_rows` to be `1`, that will automatically open the first (and only) row in that relationship container. 

![image](https://user-images.githubusercontent.com/7188159/176661686-841fa180-86d5-4ab0-acdb-37c1f445d45e.png)

![image](https://user-images.githubusercontent.com/7188159/176661636-ca92fbfc-a576-4801-aa92-dacec2eef6e2.png)

Let me know if I am missing something here.

Cheers

**Comment by pxpm** [comment]
No problem at all! Re-open if needed! 👍 

Cheers
