### ISSUE TITLE
CrudField API - get number of rows in `repeatable`?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#152]
Interesting question from Gitter:

> I get how i can use the `crud.field('xyz').subfield('abc')` selection to apply a change event or similar to every subfield matching a selection, **is there any way of identifying how many children repeats there are in a repeating field set?** eg. I want to count the total cost of invoice items individual prices... or i want to be alerted when a minimum threshold is passed, how do i find the number of rows that go in the `subfield('field',row-number)`?
> If I can avoid reinventing the crud system I'd like to.

I guess we don't actually have an official way to get the number of rows, right? How would someone do smth like this @pxpm ? 

Even if we don't provide a built-in solution, we should probably tell people how to do that, seems like a reasonable need to me.

**Comment by promatik** [comment]
@tabacitu it's easy to count the number of entries in the repeatable.

This will do it;

```js
crud.field('repeatable_example_1').wrapper.find('.repeatable-element').length
```

Should we add a feature for it?

We could add a bit of code to the JS to get this, but it would be a "hack" specially and only made for `repeatable` field, something like `children`, that would return an array of dom elements in case it is a repeatable.

**Comment by tabacitu** [comment]
Oh that easy, really? Hmm... I don't know then... I'd say it's at the border between COULD and SHOULD... let's table the decision for now... if it comes up a lot we could do it, if not... no.

Thanks @promatik !

**Comment by kronos-collector** [comment]
@vpoile_twitter here just wanted to add, that although the above is possible, I cannot target that `.find('.repeatable-element)')` unless I add a class to the container and target it in the `.find()` selector, unless I am missing something:
```
$this->crud->addField([
            'name' => 'xyz',
            'label' => 'Repeatable Item',
            'type' => 'repeatable',
            'subfields' => [
                [
                    'name' => 'subtotal',
                    'type' => 'number',
                    'label' => 'Sub total',
                    'pivot' => true,
                    'wrapper' => [
                        'class' => 'col-md-4 searchable_element',
                    ],
                ]
            ]
        ]);
```

`crud.field('xyz').wrapper.find('.searchable_element input').length` 

This is the generated HTML: 
```
<div class="col-md-4 searchable_element" element="div" bp-field-wrapper="true" bp-field-name="xyz.2.subtotal" bp-field-type="number">
    <label>Sub total</label>
            <input type="number" name="xyz[2][subtotal]" value="30" class="form-control" data-repeatable-input-name="subtotal" data-row-number="3" change-event-applied="true">
    </div>
```

I hoped that searching using `.find(input[data-repeatable-input-name="subtotal"])` might have caught it but it doesn't appear to.

This is fine, but to me makes for a fairly fragile relationship. 
I don't mind if its doesn't end up handled by the library and I'm super thankful that you guys know it inside out to point out a simple solution to the original query.

**Comment by tabacitu** [comment]
@promatik could you please point @kronos-collector (and others) in the right direction? A definitive guide to getting the number of rows in repeatable? If we have that here, I say we close this issue for now, not worth creating an API for it.

Thanks!

**Comment by promatik** [comment]
Hi @kronos-collector, sorry for the delay, I think something isn't right on your side, every repeatable entry has a `repeatable-element` class in it, even if you set up the wrapper of the subfields. Are you using the latest backpack version?

Take the example [on demo](http://127.0.0.1:8000/admin/field-monster/141/edit);
<img width="396" alt="image" src="https://user-images.githubusercontent.com/1838187/185812091-d4c2347a-a74d-4480-928d-1dcc24d5afe8.png">

Inside the repeatable wrapper, there are 3 entries, each with the "repeatable-element" class.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1838187/185812116-23b509db-cd91-4c0f-a322-4b7c3c939051.png">

That's why the code `crud.field('repeatable_example_1').wrapper.find('.repeatable-element').length` should work.
Let me know if your DOM looks different, it shouldn't I guess...

**Comment by promatik** [comment]
@kronos-collector, since this is a "won't" I'll close this one for now.
I believe my previous comment https://github.com/Laravel-Backpack/ideas/issues/152#issuecomment-1172933286 solves this issue. If you or anyone is struggling with this, we may re-open 👌
