### ISSUE TITLE
[Feature Request] Ability to add button from a closure function

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/ideas#168]
# Feature Request

### What's the feature you think Backpack should have?

In the list operation, I see `addButtonFromModelFunction` and `addButtonFromView`. Sometimes I need to add a tiny button, so I think it is good if there is something like:
`$this->crud->addButtonFromFunction($stack, $name, $closure_function, $position);`

### Have you already implemented a prototype solution, for your own project?

No. I am using `addButtonFromModelFunction` but I think it is somehow complicated.

### Do you see this as a core feature or an add-on?

No.

**Comment by tabacitu** [comment]
Haha I had a similar idea here - #149 - would that fix your problem @mamprogr ?

**Comment by mamprogr** [comment]
Yes, I think it solves the problem

**Comment by tabacitu** [comment]
Awesome, let's consolidate this into #149 then 🎉 It's something that I hope we'll get done pretty soon (1-2 months). 

Cheers!
