### ISSUE TITLE
Getting Started instructions on empty dashboard page

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#170]
After someone installs Backpack, they're greeted by an empty dashboard. They think "_ok, now what_".

Let's add a button to the sidebar. Or to the main content area. To show a special docs page on locahost. That page or modal can link to all of the things you'll most likely want to do, right there in your admin panel; you don't even have to leave the page, you just copy-paste commands form the modal here.

What do we want to show there? In what format? Let's prototype/brainstorm/have a few proposals/PRs.

**Comment by pxpm** [comment]
Hey @tabacitu .

One thing that I find very usefull are interactive tutorials ... multi-step and stuff like. Example:
```
Hey buddy! Nice to see you!
Nothing much to see here hun? Click here to start our 10 step tutorial (5min max) to get you kickstarted. (Button to click)

// STEP 1
Backpack is about building interfaces around your database data. We provide you the best tools .... tadaddada
Let's start with by creating a migration  .... you can do it dadada or you click here yo automatically generate a dummy migration file for you: (button to generate a dummy migration)


// STEP 2
Having the migration in place let's add an interface so we can create/edit records on that table. 
da da generators, check if instaled if not install, da da or click here to automatically build the crud for the previous generated dummy table

...
```
You get the idea.
The framework behind to "show the multi-step popups" could be a Backpack package, I am sure a lot of panels would benefit from a introduction to their panels. 👍 

Cheers

**Comment by tabacitu** [comment]
Closing in favor of https://github.com/Laravel-Backpack/CRUD/pull/4577

Would love second looks, alternatives or improvements
