### ISSUE TITLE
[Feature Request] Spatie Medialibrary Upload and Upload Multiple Field

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/ideas#176]
# Feature Request

### What's the feature you think Backpack should have?

Upload and Upload Multiple Field but work with spatie media library

### Have you already implemented a prototype solution, for your own project?

Hmm only for the backend part for single file collection, but not the blade field views. I think you can see mine in the gitter chat logs if u scroll up for a few days.

### Do you see this as a core feature or an add-on?

Core. Spatie MediaLibrary is pretty much the defacto library for managing file uploads in laravel projects these days.

**Comment by tabacitu** [comment]
Let's continue the conversation in https://github.com/Laravel-Backpack/ideas/issues/20
