### ISSUE TITLE
[4.1.x][Feature] Focus on first input on new repeatable group

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#18]
This is a feature we have inside the main form (see ```form_content.blade.php```), and it should be present inside the repeatable field too. It will make it much easier to add complicated entries, because your hands don't have to leave your keyboard.

Rephrased: when you click "New" inside repeatable, it adds a new input group. But you have to manually go to the first input and click it to focus on it. We can spare the user this hassle, since what they want is _most likely_ to write inside that shiny new input group, starting from the first input.

**Comment by maurohmartinez** [comment]
@tabacitu correct me if I am wrong, but I think this is something I am already working on here [#4091](https://github.com/Laravel-Backpack/CRUD/issues/4091)
If so, we can close this?

**Comment by tabacitu** [comment]
Totally.
