### ISSUE TITLE
Improve `CHANGELOG.md` for paid packages

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#199]
After @phpfour has finished https://github.com/Laravel-Backpack/ideas/issues/156 , we now have a new process for releasing new version for PRO, DevTools and EditableColumns, which will generate up-to-date changelogs for each:
    - [Backpack PRO](https://backpackforlaravel.com/products/pro-for-unlimited-projects/CHANGELOG.md)
    - [Backpack DevTools](https://backpackforlaravel.com/products/devtools/CHANGELOG.md)
    - [Backpack EditableColumns](https://backpackforlaravel.com/products/editable-columns/CHANGELOG.md)

I'm super SUPER happy we finally have this 🎉 I think it was unacceptable that we push updates every week or so, but potential buyers couldn't see that. The packages looked unmaintained, even though they were totally not.

However, there are still a few things we can improve on, in these changelogs @phpfour  
And I think a few of them are super-easy to do:
- [x] MUST - change date format to 12 January 2022 (the american format is confusing, really)
- [x] MUST - remove "Full Changelog" text and link; since our buyers don't have access to Github, that points to a 404 so it's confusing;
- [ ] SHOULD - remove ALL other links too: on version name, on PR name, on author name; they all point to 404s; if we can do that from the action/template, that's great; if not, our website already parses the Markdown before showing it, so we can add a rule to eliminate links to Github in CHANGELOG.md, or something;

---

In principle, let's consider the `CHANGELOG.md` file "_for visitors_", not for ourselves. So it should be pretty, concise, not have broken links. So I want us to go from this:
<img width="1510" alt="CleanShot 2022-08-19 at 11 12 11@2x" src="https://user-images.githubusercontent.com/1032474/185574820-238aeeb5-aad1-4b0b-9487-b3a0cca4b6df.png">

To something like this:
 
<img width="1510" alt="CleanShot 2022-08-19 at 11 17 34@2x" src="https://user-images.githubusercontent.com/1032474/185575845-81271501-6ebb-4505-b43b-0780465fb46d.png">

**Comment by tabacitu** [comment]
@phpfour any progress on this one?

**Comment by tabacitu** [comment]
Awesome! Good enough. I can't really tell what the difference is, can you please create PRs with the changes to:
- https://github.com/laravel-backpack/devtools
- https://github.com/laravel-backpack/pro
- https://github.com/laravel-backpack/editable-columns

Thanks 🙏

**Comment by phpfour** [comment]
Hey @tabacitu, sure thing...created the PRs: 

https://github.com/Laravel-Backpack/DevTools/pull/302
https://github.com/Laravel-Backpack/PRO/pull/88
https://github.com/Laravel-Backpack/editable-columns/pull/58

Thanks!

**Comment by tabacitu** [comment]
Todo: https://github.com/Laravel-Backpack/repo/issues/3

**Comment by phpfour** [comment]
Hey @tabacitu, I've made some progress on this, PR here: https://github.com/Laravel-Backpack/backpackforlaravel.com/pull/167

![image](https://user-images.githubusercontent.com/171715/199683728-99a96c5c-21d8-4939-9967-53e688c4e50f.png)

**Comment by tabacitu** [comment]
AWESOME. https://github.com/Laravel-Backpack/backpackforlaravel.com/pull/167 closes this then 🎉
