### ISSUE TITLE
[Feature Request] [Bug] Better support of non-Eloquent models

### ISSUE THREAD

**Issue by nikserg** [Laravel-Backpack/ideas#205]
# Feature Request/Bug

There is wide-used helper function:

```
if (! function_exists('backpack_users_have_email')) {
    /**
     * Check if the email column is present on the user table.
     *
     * @return string
     */
    function backpack_users_have_email()
    {
        $user_model_fqn = config('backpack.base.user_model_fqn');
        $user = new $user_model_fqn();

        return \Schema::hasColumn($user->getTable(), 'email');
    }
}
```

which assumes, that your user is Eloquent model, stored in your database, and moreover have some specific fields. Which is not mandatory. User model only should implement `\Illuminate\Contracts\Auth\Authenticatable` interface.

I have to implement this as a workaround for my project:

```
function backpack_users_have_email()
{
    return false;
}
```

because my User doesn't have email, and even doesn't store in database.

It would be nice to have better support for such cases.

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4599

Thanks again @nikserg !
