### ISSUE TITLE
[Feature Request] allow delete button on edit page

### ISSUE THREAD

**Issue by de-raaf-media** [Laravel-Backpack/ideas#208]
# Feature Request

### What's the feature you think Backpack should have?

A delete / trash button a the edit page (core feature). Actually surprised that there isn't one already.

If you have a crud object with 1000+ entries the proces to delete an entry is very cumbersome. You have to navigate to the list view. Search for the record. Check to see if it is the right one ( sometimes ;-) ). Navigate back to final be able to delete the record.

Maybe the is a reason not to include this on the edit page but I cannot think of any.

**Comment by pxpm** [comment]
Hello @de-raaf-media 

Thanks for the suggestion, I've just edited the title and moved it to the ideas repo where we pick what we are going to work next. 

Cheers

**Comment by tabacitu** [comment]
Makes total sense to me! Will do @de-raaf-media , thanks!

**Comment by maurohmartinez** [comment]
@tabacitu what do you think? Which option you prefer? Or maybe you have something else in mind?

![Screenshot 2022-12-01 at 15 55 34](https://user-images.githubusercontent.com/33960976/205072954-526829dc-7169-4801-b3f0-3dc534298eee.png)

**Comment by tabacitu** [comment]
Hmm... I think the bottom right corner makes the most sense. That'll keep the buttons all in the same general area. But separate them enough that it doesn't get click by mistake. Of course that should also have a confirmation.

**Comment by tabacitu** [comment]
Let's move the conversation to @maurohmartinez 's PR 🎉 https://github.com/Laravel-Backpack/CRUD/pull/4813

**Comment by de-raaf-media** [comment]
Very cool! Thanks guys!
