### ISSUE TITLE
[Feature Request] Ability to change the column title based on the results

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/ideas#214]
# Feature Request

### What's the feature you think Backpack should have?

I find it good to have the ability to write to the column header and footer based on the filtered results.
For example, I need to calculate the sum of the elements of a particular column and write the result in the footer of the column as shown in the picture:
![image](https://user-images.githubusercontent.com/734475/189844608-f2a7adcc-493b-432b-a561-820a7420de31.png)

### Have you already implemented a prototype solution, for your own project?

Currently, I've created a button at the top of the page that just refreshes the page and changes the column name based on the results.
But this solution entails pressing this button every time I filter the results.

### Do you see this as a core feature or an add-on?

I think it should be a core feature.

**Comment by tabacitu** [comment]
Hey guys - jumping in. 

I see where this would be useful, but I don't think we _can_ or _should_ provide a native way to do that in the core. The possibilities are endless, so no matter what solution we offer... it won't be enough. 

Fortunately, even thought it's not exactly a one-line solution, this can easily be solved with existing functionality, we can just:
- [add a `script` widget to the page](https://backpackforlaravel.com/docs/5.x/base-widgets#script-1)
- in that script, select that heading and change it to your liking;

Hope it helps.
Cheers!
