### ISSUE TITLE
Check for form changes when changing edit language and warn user that they will be lost if not saved

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/ideas#239]
I'm using some multi-language fields following guide:
https://backpackforlaravel.com/docs/5.x/crud-operation-update#translatable-models-and-multi-language-cruds

I've found this issues:
1. i'd like to choose what languages to support, now i see always English, French, Italian, Romanian, how can i set them?
2. Changing language you lost values, you always need to Save, is there a way to save on lang change?

### Is it a bug in the latest version of Backpack?
also previous versions

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 29 2022 02:51:04) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.43.0@011f2e1d49a11c22519a7899b46ddf3bc5b0f40b

### BACKPACK VERSION:
5.4.11@ffbadcdb6478822646600b2cd763490caa927155

**Comment by alexsol22** [comment]
> Heads-up guys - we already have `CRUD::set('warnBeforeLeaving', true)` - isn't that a reasonable solution for this? See https://backpackforlaravel.com/docs/5.x/release-notes#warning-before-leaving-the-create-or-update-form

interesting, I did the composer update added this functionality in the setupCreateOperation() but it doesn't do anything.. it should show a warning when you leave the module right?

**Comment by tabacitu** [comment]
![perfection_cap](https://user-images.githubusercontent.com/1032474/207428403-77420972-7c63-4d06-b053-84f13bc9d05d.gif)
