### ISSUE TITLE
[Feature Request] A way to add Javascript or CSS to just one Operation page, for a particular CRUD

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#4]
# Feature Request

### What's the feature you think Backpack should have?

We already [have a way to add Javascript or CSS to ALL admin panel pages](https://backpackforlaravel.com/docs/4.1/base-how-to#add-custom-javascript-to-all-admin-panel-pages). 

And developers can also:
- edit the `public/packages/backpack/crud/js/create.js` file for example, to add some JS to the Create operation;
- edit the `public/packages/backpack/crud/css/create.css` file for example, to add some CSS to the Create operation;

But because there's this one css/js file for that operation, it gets loaded for ALL CRUDs. Which is not what you need, sometimes. I think we could use a more flexible way of including custom CSS/JS files inside operations.

How about if we create a Widget that allows you to push things inside the `before_styles`, `after_styles`, `before_scripts` and `after_scripts` stacks? The way I see it, you could do something like:

```php
    // To include custom JS from a blade file
    Widget::add()->type('script')->stack('after_scripts')->view('path.to.a.certain.view');

    // To include custom JS from a JS file - public/assets/js/some_custom_thing.js
    Widget::add()->type('script')->stack('after_scripts')->file('assets/js/some_custom_thing.js');

    // To include custom CSS from a blade file
    Widget::add()->type('style')->stack('after_styles')->view('path.to.a.certain.view');

    // To include custom CSS from a CSS file - public/assets/js/some_custom_thing.css
    Widget::add()->type('style')->stack('after_styles')->file('assets/css/some_custom_thing.css');
```

I think the above would be pretty easy to create as a non-breaking change. And it would allow a lot more flexibility. I'm open to different ways of implementing this - the Widget solution is something I just came up with.

Alternatively (or additionally) we could create a syntax inside CRUD that also does the above:
```php
CRUD::addScriptFile('assets/js/some_custom_thing.js');
CRUD::removeScriptFile('assets/js/some_custom_thing.js');

CRUD::addStyleFile('assets/css/some_custom_thing.css');
CRUD::removeStyleFile('assets/css/some_custom_thing.css');
```

Not sure this is needed though - it might complicate the process unnecessarily, when behind the scenes it's doing the same thing - adding a widget.

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core Feature

**Comment by timbertens** [comment]
I just had a case where this functionality would be very handy !

**Comment by MeerKatDev** [comment]
This would be amazing to have
```php
CRUD::addScriptFile('assets/js/some_custom_thing.js');
CRUD::removeScriptFile('assets/js/some_custom_thing.js');
```

**Comment by tabacitu** [comment]
Update: we've just added `script` and `style` widgets to Backpack 4.2 - https://github.com/Laravel-Backpack/CRUD/pull/3912

Currently the working syntax is:
```php
Widget::add()->type('script')->content('assets/js/custom-script.js');
Widget::add()->type('style')->content('assets/css/custom-style.css'); 
```

We _could_ add a few convenience methods to CRUD too... like @MeerKatDev suggested.... but... I don't think there's a real reason to include that in the `CRUD` class (other than convenience):
- If they're Widgets, you can use them outside CRUD pages too (eg. dashboards, custom pages, etc). 
- If we use the `CRUD::addScriptFile()`... that would only work inside CRUD pages.

I think a better approach would be to refrain from adding convenience methods inside CRUDs, and nudge people into adding Widgets for this. So I'm going to close the issue for now.

Of course, this decision is up to debate. I see @MeerKatDev 's post has 5 likes, so if any of you guys think I'm wrong, and it's inconvenient to use widgets, please let me know and we'll reopen and discuss.

Cheers and thanks a lot for the feedback and the patience!
