### ISSUE TITLE
[Improvement] CRUD fields  - allow devs to leave out "label"; correctly specify "for" attribute on label and input

### ISSUE THREAD

**Issue by rabol** [Laravel-Backpack/ideas#42]
if one forget to add the 'label' property of a field, an error is thrown when the field is rendered.

if the 'label' proberty is empty, a <label></label> tag is rendred - if the label is empty, there is no need to render the tag.

it is not possible to set the 'for' property of the <label>tag

**Comment by tabacitu** [comment]
Well this hasn't seen any action in a while... @rabol I'm sure you know that nowadays you can leave out the "label" when defining fields. We still haven't gotten to add the correct "for" on labels, but we have an issue for that specifically, so let's close in favor of that one - https://github.com/Laravel-Backpack/ideas/issues/86

Cheers!
