### ISSUE TITLE
[4.1][Feature] A way to tell Backpack "don't overwrite my field name"

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#65]
Separated this issue from Laravel-Backpack/CRUD#3065 

🟨 Problem 1 B - no way to tell Backpack "don't overwrite my field name"

- mentioned by @tabacitu in Laravel-Backpack/CRUD#3065 (comment)
- we should probably provide a way for the developer to take complete control over this (aka disable the new behaviour in 4.1 where we overwrite the field name), even if it's not exactly this solution;

**Comment by pxpm** [comment]
@tabacitu this is working for me, it prevents Backpack from infering stuff.

```php
$this->crud->addField([
            'name' => 'refresh_id', // refresh() is a Laravel model function
            'entity' => false
        ]);
```
I am going to close this.
