### ISSUE TITLE
[Feature Request] Repeatable column type

### ISSUE THREAD

**Issue by jrbecart** [Laravel-Backpack/ideas#75]
# Feature Request

### What's the feature you think Backpack should have?

?? Display multiple values in column of type table from a repeatable type field with a select2_array field with multiple values (for example).

field example ([repeatable](https://backpackforlaravel.com/docs/4.1/crud-fields#repeatable)):
``` field example
[   // repeatable
  'name'  => 'mycolumnname',
  'label' => '...',
  'type'  => 'repeatable',
  'fields' => [
      [
          'name'    => 'myarrayfield',
          'type'        => 'select2_from_array',
          'options'     => ['A' => 'A', 'B' => 'B', 'C' => 'C'],
          'label'   => 'Value',
          'wrapper' => ['class' => 'form-group col-md-4'],
          'allows_multiple' => true,
      ],
  ]
]
```

column example ([table](https://backpackforlaravel.com/docs/4.1/crud-columns#table)):
``` column example
[
    'name'  => 'mycolumnname', 
    'label' => '...', 
    'type'  => 'table', 
    'columns' => [
        'myarrayfield[]'    => 'myarrayfield',
    ]
]
```

### Have you already implemented a prototype solution, for your own project?

?? Yes

 ```php

// File src/resources/views/crud/columns/table.blade.php 
// Added new condition and implode of the array, see comment in code

@php
    $value = data_get($entry, $column['name']);
    // make sure columns are defined
    if (!isset($column['columns'])) {
        $column['columns'] = ['value' => "Value"];
    }
    $columns = $column['columns'];
    // if this attribute isn't using attribute casting, decode it
    if (is_string($value)) {
        $value = json_decode($value);
    }
@endphp

<span>
    @if ($value && count($columns))

        @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_start')

        <table class="table table-bordered table-condensed table-striped m-b-0">
		<thead>
			<tr>
				@foreach($columns as $tableColumnKey => $tableColumnLabel)
                    @if( !is_array($tableColumnLabel))
                    <th>{{ $tableColumnLabel }}</th>
                    @endif
                @endforeach
            </tr>
        </thead>
        <tbody>
        @foreach ($value as $tableRow)
        <tr>
        @foreach($columns as $tableColumnKey => $tableColumnLabel)
        <td>

        @if( is_array($tableRow) && isset($tableRow[$tableColumnKey])  )

                @if(!is_array($tableRow[$tableColumnKey]))  // New condition
                    {{ $tableRow[$tableColumnKey] }}
                @else
                    {{ implode(", ",$tableRow[$tableColumnKey]) }} // Display array values as string 
                @endif

            @elseif( is_object($tableRow) && property_exists($tableRow, $tableColumnKey) )

                @if(!is_array($tableRow->{$tableColumnKey}))  
                   {{ $tableRow->{$tableColumnKey} }}
               @else
                   {{ implode(", ",$tableRow->{$tableColumnKey}) }}
               @endif

        @endif

    </td>
    @endforeach
</tr>
@endforeach
</tbody>
</table>

@includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_end')

@endif
</span>

```

### Do you see this as a core feature or an add-on?

?? Core

**Comment by jrbecart** [comment]
Thanks for the update.

I would say to pay attention to the column definition, don't forget the `[]` sign:
`'columns' => [
        'myarrayfield[]'    => 'myarrayfield',
]`

Also values of the array must not be an array or it will return a notice: `Array to string conversion in...`
This should always be the case, but we may be aware of it if needed.

Another thing that may be nice to have is to specify the delimiter if someone wants something different than the comma character. Other than this, for my cases it works perfectly,

Thanks again

**Comment by tabacitu** [comment]
@adriallongarriu no progress so far. But it's DEFINITELY something we'll be fixing in 5.x. Basically, we'll have a corresponding column type for each field type. `repeatable` included. 

Right now we're still knee-deep in fixing launch issues, but as soon as that's done we'll be adding new features like this one! 💪 Please use your own closure until we provide an official solution.

**Comment by tabacitu** [comment]
Update: @pxpm has been working on it for the past few weeks, and we'll be merging the `repeatable` column type in Feb 2023, as part of the Backpack v6 release. It won't only have a `repeatable`, but it'll have a column type for EVERY field type 😱

**Comment by tabacitu** [comment]
In fact, I just merged Pedro's PR that adds this column 🎉 It's closed-source, but it's ready.

https://github.com/Laravel-Backpack/PRO/pull/104

It'll be available starting Feb 2023, after we launch v6 🎉
