### ISSUE TITLE
[Feat] Repeatable should have default "elements instances" to zero

### ISSUE THREAD

**Issue by LemarinelNet** [Laravel-Backpack/ideas#81]
# Feature Request

I have a repeatable field on my product CRUD page.
This repeatable field can contain ZERO or more rows.
When I create a product which does not need "sub" items (zero repeatable element), I must first go to my repeatable field, and remove the default added row. 
That's pretty annoying ;)

I think there should be an attribute on the field to set the default row count (0 or 1), or to set if there must be a default line created (true/false)
PS : as a work around, I had to add code in the save method to ignore empty repeatable lines (...Thus this is also true that I have to handle user that add a line and doesn't fill it !!)

### Have you already implemented a prototype solution, for your own project?

No.

### Do you see this as a core feature or an add-on?

Core : new attribute to the repeatable field.

**Comment by stevebeyatte** [comment]
+1

**Comment by tabacitu** [comment]
Thanks for the bump @stevebeyatte . You can define `"init_rows" => 0` nowadays to get that ([docs here](https://backpackforlaravel.com/docs/4.1/crud-fields#repeatable-1)). But I agree, we should probably default to zero on this, and now in 4.2 might be a good time to do this. Tagging appropriately so we don't forget.

**Comment by pxpm** [comment]
Thanks for pitching in @tabacitu ! 

I don't agree with making this default 0 rows. 

My reasoning is:
- If you add a field, `majority` of times you want the field to be filled. Allowing it to be empty should be the exception, not the rule. 
- "hidden" fields is not the norm, people are not prepared to "click to show fields" but more prepared to "click "X" to delete". 

So I am in for default 1 row, configurable as we have it now. 

Pedro

**Comment by tabacitu** [comment]
Hmm... you make a good point. @promatik what's your point on this? Default zero or default one?

**Comment by tabacitu** [comment]
Since clicking on "Add Item" doesn't place the focus on the first field (yet), this has an extra inconvenience - that using keyboard alone the UX will suffer.

I'm going to postpone this until v12, maybe we do it then.

**Comment by tabacitu** [comment]
This is now done - `repeatable` now defaults to zero items. Thanks for letting us know @LemarinelNet !
