### ISSUE TITLE
Field improvement proposals - for, setLabelFromFormRequest and others

### ISSUE THREAD

**Issue by nekulin** [Laravel-Backpack/ideas#88]
# Feature Request

### What's the feature you think Backpack should have?

Field to improve

### Have you already implemented a prototype solution, for your own project?

yes

### Do you see this as a core feature or an add-on?

no

When I use Field, you don't have label for `<label for="{{ $field['name'] }}">`

Why do I have to describe `CRUD::field('currency')->label('...')` every time? I already described this in CurrencyRequest

```
public function attributes()
{
return [
 'currency' => 'Currency custom',
 ];
 }
```

You have repetition everywhere in filed `<label>{!! $field['label'] !!}</label>` why not take out these parts separately and make a template. Can use laravelcollective html

```
<label for="{{ $field['name'] }}">
    {{ __('validation.attributes.' . $field['name']) }}
</label>
```

The problem is still different, it is convenient to generate fields in the controller, but there are many problems when I need to make my own custom view, I have to transfer a lot of your code. It is better to make a widget that will work with your forms and table

**Comment by nekulin** [comment]
Label that is generated automatically is not always suitable and I need to translate it how should I do it ? I have to specify `__('Currency')` everywhere so that it substitutes the desired label from the language ?

I use label Currency in
index
view
create
update

**Comment by nekulin** [comment]
The big problem is you have a custom view, I want to display additional information on the create page, I can't do this, I have to do something like this

```
@extends(backpack_view('blank'))

@php
  $defaultBreadcrumbs = [
    trans('backpack::crud.admin') => url(config('backpack.base.route_prefix'), 'dashboard'),
    $crud->entity_name_plural => url($crud->route),
    trans('backpack::crud.add') => false,
  ];

  // if breadcrumbs aren't defined in the CrudController, use the default breadcrumbs
  $breadcrumbs = $breadcrumbs ?? $defaultBreadcrumbs;
@endphp

@section('header')
	<section class="container-fluid">
	  <h2>
        <span>{!! $crud->getHeading() ?? $crud->entity_name_plural !!}</span>

        @if ($crud->hasAccess('list'))
          <small><a href="{{ url($crud->route) }}" class="d-print-none font-sm"><i class="la la-angle-double-{{ config('backpack.base.html_direction') == 'rtl' ? 'right' : 'left' }}"></i> {{ trans('backpack::crud.back_to_all') }}</a></small>
        @endif
	  </h2>
	</section>
@endsection

@section('content')

<div class="row">
	<div class="{{ $crud->getCreateContentClass() }}">
		<!-- Default box -->

		  <form method="post"
		  		action="{{ url($crud->route) }}"
				@if ($crud->hasUploadFields('create'))
				enctype="multipart/form-data"
				@endif
		  		>
			  {!! csrf_field() !!}

              @include('crud::form_content', [ 'fields' => $crud->fields(), 'action' => 'create' ])

	          @include('crud::inc.form_save_buttons')
		  </form>
	</div>
</div>
`@extends(backpack_view('blank'))

@php
  $defaultBreadcrumbs = [
    trans('backpack::crud.admin') => url(config('backpack.base.route_prefix'), 'dashboard'),
    $crud->entity_name_plural => url($crud->route),
    trans('backpack::crud.add') => false,
  ];

  // if breadcrumbs aren't defined in the CrudController, use the default breadcrumbs
  $breadcrumbs = $breadcrumbs ?? $defaultBreadcrumbs;
@endphp

@section('header')
	<section class="container-fluid">
	  <h2>
        <span>{!! $crud->getHeading() ?? $crud->entity_name_plural !!}</span>

        @if ($crud->hasAccess('list'))
          <small><a href="{{ url($crud->route) }}" class="d-print-none font-sm"><i class="la la-angle-double-{{ config('backpack.base.html_direction') == 'rtl' ? 'right' : 'left' }}"></i> {{ trans('backpack::crud.back_to_all') }}</a></small>
        @endif
	  </h2>
	</section>
@endsection

@section('content')

<div class="row">
	<div class="{{ $crud->getCreateContentClass() }}">
		<!-- Default box -->

		  <form method="post"
		  		action="{{ url($crud->route) }}"
				@if ($crud->hasUploadFields('create'))
				enctype="multipart/form-data"
				@endif
		  		>
			  {!! csrf_field() !!}

              @include('crud::form_content', [ 'fields' => $crud->fields(), 'action' => 'create' ])

	          @include('crud::inc.form_save_buttons')
		  </form>
	</div>
</div>

@endsection

`
@endsection
```

I would like to make it easier

```
@section('content')

<div class="row">
 
 {{ $crud }}
 
 
</div>

@endsection
```

**Comment by tabacitu** [comment]
Sorry @nekulin but I still don't understand - must be the language barrier, I really don't get what you're trying to achieve. I'm going to close this issue, as it doesn't look like it's going anywhere, but maybe this helps:
- yes, you can specify `__('label_name')` for the label name, it's perfectly fine;
- to display additional information on the Create view, you should either use Widgets or custom fields;

Sorry I couldn't be of more help, but it's really difficult to understand and help from the information we have. 
Cheers!
