### ISSUE TITLE
Pass validation rules to fields

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#95]
What if the Create/Update operation could construct a FormRequest out of the CRUD object, and use that instead? Or something like that.

The bottom line is, what if we could specify the validation `rules`, `attributes` and `messages` inside the field definition? So instead of having a CrudPanel made up of 4 items:
- route line
- controller file
- form request file
- model file

It would be made up of only 3 items:
- route line
- controller file
- model file

Wouldn't that simplify writing CRUDs? Does anybody _actually_ reuse their FormRequest files? I'm wondering.

```php
// maybe something like this, in singular
CRUD::field('name')
             ->validationRule('required')
             ->validationAttribute('full name')
             ->validationMessage('You gotta fill this in man');

// also thanks to CrudField we could now also do shorthands/aliases, something like
CRUD::field('name')->mustBe('required'); // or
CRUD::field('name')->validate('required'); // or
CRUD::field('number')->valid('number');
```

This is a first idea for a syntax/implementation, I'm just brainstorming here 😀

**Comment by promatik** [comment]
Neat 😁
I think I'll keep on using requests, I like the idea of packing validations on a request, it's organized and most of the times I end up adding some other stuff there.
Anyway, this is a cool feature many users may use.

I vote for `validate` shortcut only, like this;
```php
CRUD::field('name')->validate('required');
CRUD::field('name')->validate('required', 'A name is required');
CRUD::field('name')->validate('required|unique:posts|max:255');

// or array
CRUD::field('name')->validate(['required', 'unique:posts', 'max:255']);
CRUD::field('name')->validate([
    'required' => 'A name is required',
    'unique:posts',
    'max:255'
]);

// or functional one by one
CRUD::field('name')
    ->validate('required', 'A name is required')
    ->validate('unique:posts')
    ->validate('max:255');
```

Maybe we should also provide `validateOnUpdate` and `validateOnCreate`?

**Comment by tabacitu** [comment]
This is done in Backpack v5 - see https://backpackforlaravel.com/docs/5.x/crud-operation-create#validating-fields-using-field-attributes

Past us were pretty smart 😀
