### ISSUE TITLE
[Feature Request] ListOperation - ability to show actions column before/after all other columns

### ISSUE THREAD

**Issue by enefeka** [Laravel-Backpack/ideas#96]
# Feature Request

### What's the feature you think Backpack should have?

I don't know if this is possible, but I couldn't find it's documentation anywhere, nor it's code implementation. But it seems that it's not possible to make the "actions" column be the first column of the table?

I've tried using operations from the Cheat sheet to achieve this but none of them worked.

Is there any way as of today to easily achieve this?

**Comment by tabacitu** [comment]
Since this saw no action until now, I'm going to assume not many people need it, and close the issue. If someone googles, lands on this and thinks we should reconsider, please say so and we might re-open.

Cheers!
